---
title: "EXP-DELAY-MARGIN"
author: "Lei"
date: "2022-10-08"
output: pdf_document
---

```{r message=FALSE}
library(EnvStats)
library(dplyr)
library(tidyverse)
library(ggplot2)
source("Supp_functions.R")
```


```{r}
TT = 2e4
MC = 1e3
d  = 2
mu_Choice = list(
  NoMargin = c(0.5, 0.5),
  WeakMargin = c(0.6, 0.5),
  StrongMargin = c(1, 0.5)
    )
alpha = 0.5
partial = c(0.5, 1)
```

```{r}
opts = list(
  delay_dist = c("PARETO", "PARETO"),
  pmt = c(0.75, 1.25),
  partial = partial
)

record_PARETO_MARGIN = list(
  mu_Choice_1 = list(arm1 = list(), arm2 = list()),
  mu_Choice_2 = list(arm1 = list(), arm2 = list()),
  mu_Choice_3 = list(arm1 = list(), arm2 = list())
)

for (ind in 1:2){
  for (mc in 1:MC){
    DAT = eps_greedy(TT, d, mu_Choice[[ind]], alpha, opts)
    
    # first arm
    target_arm = 1
    
    # ipw
    res_1_ipw = report_est(DAT$Y, DAT$A, DAT$D, e=DAT$e[target_arm,], 
                       muhat = rep(0, TT), a=target_arm)
    # delay-oracle
    # res_1_oracle = report_est(DAT$Y, DAT$A, DAT$D, e=DAT$e[target_arm,], 
    #                   muhat = rep(0, TT), a=target_arm,
    #                   opts = list(pD = partial[target_arm]))
    
    # avg as muhat
    res_1_avg = report_est(DAT$Y, DAT$A, DAT$D, e=DAT$e[target_arm,], 
                       muhat = DAT$AVG[target_arm, ], a=target_arm)
    
    record_PARETO_MARGIN[[ind]]$arm1[[mc]] = list(res_1_ipw, res_1_avg)
    
    # second arm
    target_arm = 2
    
    # ipw
    res_2_ipw  = report_est(DAT$Y, DAT$A, DAT$D, e=DAT$e[target_arm,], 
                       muhat = rep(0, TT), a=target_arm)
    # delay-oracle
    # res_2_oracle = report_est(DAT$Y, DAT$A, DAT$D, e=DAT$e[target_arm,], 
    #                   muhat = rep(0, TT), a=target_arm,
     #                  opts = list(pD = partial[target_arm]))
    
    # avg as muhat
    res_2_avg  = report_est(DAT$Y, DAT$A, DAT$D, e=DAT$e[target_arm,], 
                       muhat = DAT$AVG[target_arm, ], a=target_arm)
    
    record_PARETO_MARGIN[[ind]]$arm2[[mc]] = list(res_2_ipw, res_2_avg)
  }
}
```

```{r}
saveRDS(record_PARETO_MARGIN, file = "record_PARETO_MARGIN.RDS")
```

```{r}
record_PARETO_MARGIN = readRDS("record_PARETO_MARGIN.RDS")
```


```{r}
# output results
record = readRDS("record_PARETO_MARGIN.RDS")

# no margin
record_NoMargin = data.frame(
  IPW  = rep(0, MC),
  AIPW = rep(0, MC),
  Mean = rep(0, MC),
  NH   = rep(0, MC)
)
for (mc in 1:MC){
  ## IPW
  arm1_est = record$mu_Choice_1$arm1[[mc]][[1]]$est[1]
  arm1_var = record$mu_Choice_1$arm1[[mc]][[1]]$var_est[1]
  arm2_est = record$mu_Choice_1$arm2[[mc]][[1]]$est[1]
  arm2_var = record$mu_Choice_1$arm2[[mc]][[1]]$var_est[1]
  record_NoMargin$IPW[mc] = (arm1_est - arm2_est)/sqrt(arm1_var + arm2_var)
  
  ## AIPW
  arm1_est = record$mu_Choice_1$arm1[[mc]][[2]]$est[1]
  arm1_var = record$mu_Choice_1$arm1[[mc]][[2]]$var_est[1]
  arm2_est = record$mu_Choice_1$arm2[[mc]][[2]]$est[1]
  arm2_var = record$mu_Choice_1$arm2[[mc]][[2]]$var_est[1]
  record_NoMargin$AIPW[mc] = (arm1_est - arm2_est)/sqrt(arm1_var + arm2_var)
  
  ## Mean
  arm1_est = record$mu_Choice_1$arm1[[mc]][[1]]$est[4]
  arm1_var = record$mu_Choice_1$arm1[[mc]][[1]]$var_est[4]
  arm2_est = record$mu_Choice_1$arm2[[mc]][[1]]$est[4]
  arm2_var = record$mu_Choice_1$arm2[[mc]][[1]]$var_est[4]
  record_NoMargin$Mean[mc] = (arm1_est - arm2_est)/sqrt(arm1_var + arm2_var)
  
  ## NH
  arm1_est = record$mu_Choice_1$arm1[[mc]][[2]]$est[3]
  arm1_var = record$mu_Choice_1$arm1[[mc]][[2]]$var_est[3]
  arm2_est = record$mu_Choice_1$arm2[[mc]][[2]]$est[3]
  arm2_var = record$mu_Choice_1$arm2[[mc]][[2]]$var_est[3]
  record_NoMargin$NH[mc] = (arm1_est - arm2_est)/sqrt(arm1_var + arm2_var)
  
  ## IAD
  arm1_est = record$mu_Choice_1$arm1[[mc]][[1]]$est[2]
  arm1_var = record$mu_Choice_1$arm1[[mc]][[1]]$var_est[2]
  arm2_est = record$mu_Choice_1$arm2[[mc]][[1]]$est[2]
  arm2_var = record$mu_Choice_1$arm2[[mc]][[1]]$var_est[2]
  record_NoMargin$IAD[mc] = (arm1_est - arm2_est)/sqrt(arm1_var + arm2_var)
  
  ## NH-0
  arm1_est = record$mu_Choice_1$arm1[[mc]][[1]]$est[3]
  arm1_var = record$mu_Choice_1$arm1[[mc]][[1]]$var_est[3]
  arm2_est = record$mu_Choice_1$arm2[[mc]][[1]]$est[3]
  arm2_var = record$mu_Choice_1$arm2[[mc]][[1]]$var_est[3]
  record_NoMargin$NH0[mc] = (arm1_est - arm2_est)/sqrt(arm1_var + arm2_var)
}

record_NoMargin = record_NoMargin %>% gather(key = "Estimator", value = "value")
position_x = rep(seq(-4, 4, length.out = MC), 6)
normal_density = dnorm(position_x)
record_NoMargin = cbind(record_NoMargin, position_x, normal_density)

ggplot(record_NoMargin, aes(x = value)) +
  geom_histogram(aes(y = ..density..), binwidth = 0.2) +
  geom_line(aes(x = position_x, y = normal_density)) +
  facet_wrap(vars(Estimator), ncol = 2, scales = "free") +
  theme_minimal() +
  ylab("")
```


```{r}
# output results
record = readRDS("record_PARETO_MARGIN.RDS")

# weak margin
record_WeakMargin = data.frame(
  IPW  = rep(0, MC),
  AIPW = rep(0, MC),
  Mean = rep(0, MC),
  NH   = rep(0, MC)
)
for (mc in 1:MC){
  ## IPW
  arm1_est = record$mu_Choice_2$arm1[[mc]][[1]]$est[1]
  arm1_var = record$mu_Choice_2$arm1[[mc]][[1]]$var_est[1]
  arm2_est = record$mu_Choice_2$arm2[[mc]][[1]]$est[1]
  arm2_var = record$mu_Choice_2$arm2[[mc]][[1]]$var_est[1]
  record_WeakMargin$IPW[mc] = (arm1_est - arm2_est - 0.1)/sqrt(arm1_var + arm2_var)
  
  ## AIPW
  arm1_est = record$mu_Choice_2$arm1[[mc]][[2]]$est[1]
  arm1_var = record$mu_Choice_2$arm1[[mc]][[2]]$var_est[1]
  arm2_est = record$mu_Choice_2$arm2[[mc]][[2]]$est[1]
  arm2_var = record$mu_Choice_2$arm2[[mc]][[2]]$var_est[1]
  record_WeakMargin$AIPW[mc] = (arm1_est - arm2_est - 0.1)/sqrt(arm1_var + arm2_var)
  
  ## Mean
  arm1_est = record$mu_Choice_2$arm1[[mc]][[1]]$est[4]
  arm1_var = record$mu_Choice_2$arm1[[mc]][[1]]$var_est[4]
  arm2_est = record$mu_Choice_2$arm2[[mc]][[1]]$est[4]
  arm2_var = record$mu_Choice_2$arm2[[mc]][[1]]$var_est[4]
  record_WeakMargin$Mean[mc] = (arm1_est - arm2_est - 0.1)/sqrt(arm1_var + arm2_var)
  
  ## NH
  arm1_est = record$mu_Choice_2$arm1[[mc]][[2]]$est[3]
  arm1_var = record$mu_Choice_2$arm1[[mc]][[2]]$var_est[3]
  arm2_est = record$mu_Choice_2$arm2[[mc]][[2]]$est[3]
  arm2_var = record$mu_Choice_2$arm2[[mc]][[2]]$var_est[3]
  record_WeakMargin$NH[mc] = (arm1_est - arm2_est - 0.1)/sqrt(arm1_var + arm2_var)
}

record_WeakMargin = record_WeakMargin %>% 
  gather(key = "Estimator", value = "value")
position_x = rep(seq(-4, 4, length.out = MC), 4)
normal_density = dnorm(position_x)
record_WeakMargin = cbind(record_WeakMargin, position_x, normal_density)

ggplot(record_WeakMargin, aes(x = value)) +
  geom_histogram(aes(y = ..density..), binwidth = 0.2) +
  geom_line(aes(x = position_x, y = normal_density)) +
  facet_wrap(vars(Estimator), ncol = 2, scales = "free") +
  theme_minimal() +
  ylab("")
```






